Move results out of Solver and use generic numeric code (select f32/f64)
srenevey/ode-solvers pull request #24
Opened 2024-01-01 20:51 UTC by DarthB

The changes in this pull request are:

- Use a data structure to store the `SolverResults` move result as suggested in #23 works.
- Overwork the code to support both f32 and f64. This fixes #20 
- Add a new example for a bouncing ball.

There have been many changes as the generic code needs us to write T::from(0.23).unwrap() for any number that is not zero or one. I did not find another solution but if someone knows a way to make the code a bit shorter I'm happy to hear about it.

2024-01-06 20:07 UTC, srenevey requested changes
Thanks for the changes, that was more work than I anticipated. I've left a few comments, mostly nitpicks. Once they've been addressed and the PR merged I'll bump the version and publish a new revision on crates.io. Thanks again for your contribution!

2024-01-13 14:20 UTC, DarthB commented on src/rk4.rs
> +            half_step: step_size / T::from_f32(2.).unwrap(),
Probably yes, just fixed it to stick to T - it's also good to not convert betwen f32 and f64 needlessly when the caller has decided for a precision

2024-01-13 14:31 UTC, DarthB commented
Thank you for the good feedback. That was my first contribution to open-source and I liked it a lot. 

So if anything was meant different in the process let me know. I asked because I just saw that I did resolve your comments (I used it as todo list) and wonder if that wasn't meant that way. 

Have a nice weekend
Tim

2024-01-14 01:34 UTC, srenevey approved these changes
Thanks for addressing my comments.

2024-01-14 01:35 UTC, srenevey commented
Thank you for submitting a second revision and addressing my comments. Everything looks good now.

Best,
Sylvain

2024-01-14 01:37 UTC, merged